### ISSUE TITLE
Add metas for Arrays

### ISSUE THREAD

**Issue by throrin19** [yoitsro/joigoose#14]
Hi,

I have a problem with joigoose convertion to mongoose schema with the usage of subCollection.

Basically, mongoose add, in subCollection element, an automated `_id` attribute and, in most cases, I don't want this.

In mongoose schema, to stop this, I have this code :

```javascript
var fieldsSchema = mongoose.Schema({ 
    d       : { type : Date }, // Date
    sa      : [ { type : String } ],
}, { _id : false, autoIndex : false });

var schema = mongoose.Schema({
    f : [ fieldsSchema ]
});
```

It's possible for the `Joi.array()` to add the mongoose schema options in meta ?

This is the list of all possibly options : https://www.quora.com/What-are-all-the-options-that-can-be-used-when-creating-a-mongoose-schema-for-mongodb

**Comment by microcipcip** [comment]
Related to this, I tried to add the options `timestamps` to the main object but didn't work. Maybe Joioose doesn't support options?
