### ISSUE TITLE
Not able to create compound index

### ISSUE THREAD

**Issue by brunoluiz** [yoitsro/joigoose#15]
It's not possible to create compound index like

```
schema.index({ locationId: 1, date: 1 }, { unique: true })
```

**Comment by yoitsro** [comment]
Please can you add the full context of how you're using Joigoose in relation to that?

**Comment by vascofg** [comment]
Any updates on this?

**Comment by yoitsro** [comment]
@vascofg Please could you add a simple example of how you're using Joigoose and how you're expecting this to work?

**Comment by vascofg** [comment]
At the moment I have a schema:
``` 
const joiSchema {
  name: Joi.string(),
  room: Joi.string().meta({ type: 'ObjectId', ref: 'Room' }),
  ...
}
```
And on the mongoose side, I have:
```
const Schema = new mongoose.Schema(Joigoose.convert(joiSchema));

Schema.index({ name: 1, room: 1 }, { unique: true });
```

Maybe we could specify indexes as `meta` on the main Joi schema object, like:
```
const joiSchema = Joi.object().keys({
  name: Joi.string(),
  room: Joi.string().meta({ type: 'ObjectId', ref: 'Room' }),
  ...
}).meta({ indexes: [
  {
    { name: 1, suite: 1 }, { unique: true },
    ...
  }
]})
```
What do you think?

**Comment by yoitsro** [comment]
Cheers @vascofg. I think that if support for adding indexes is added, then there other things which should be supported too, namely everything here: http://mongoosejs.com/docs/api.html#schematype_SchemaType

But then the difficulty is how far is reasonable to go? And if I implement everything, I may as well just have another special mongoose specific key on the Joi meta object which simply gets passed straight through as the options for that schema.

For example:

```
const joiUserSchema = Joi.object({
    name: Joi.object({
        first: Joi.string().required(),
        last: Joi.string().required()
    }),
    email: Joi.string().email().required(),
    bestFriend: Joi.string().meta({ _mongoose: { type: 'ObjectId', ref: 'User' } }),
    addresses: Joi.array().items({
        line1: Joi.string().required(),
        line2: Joi.string()
    }).meta({ _mongoose: { _id: false, timestamps: true } })
});
```

In hindsight, this is probably how I should have implemented it in the first place! What do you think?

**Comment by microcipcip** [comment]
@yoitsro That would be great, I thnik it should be implemented like that :)

**Comment by vascofg** [comment]
@yoitsro Sorry for the late response, yes I think that makes sense since we may want to use meta for other things other than specifying mongoose options.

**Comment by yoitsro** [comment]
I'm super busy with some other things right now, but feel free to send a pull request with those changes. I know that's a rubbish response, _but_ any help would be greatly appreciated.

**Comment by g-div** [comment]
I also like the idea to use .meta() for other purposes beside joigoose.
Maybe #33 can be a good start here...

**Comment by yoitsro** [comment]
Closed by https://github.com/yoitsro/joigoose/pull/33
