### ISSUE TITLE
How add empty object and arrays

### ISSUE THREAD

**Issue by microcipcip** [yoitsro/joigoose#19]
How do you set empty objects and arrays with joigoose? Usually when I try to set defaults I don't get any value saved in the mongo database.

**Comment by yoitsro** [comment]
What does your schema look like?

**Comment by microcipcip** [comment]
```
const testSchema = schema(
  joi.object({
    title: joi.string().required(),
    activity: joi.object({
      title: joi.string()
    }).default({})
  })
)

// result
{
  id: ObjectId("asdasd...")
  title: "title here"
}
```

An array works though:
```
const testSchema = schema(
  joi.object({
    title: joi.string().required(),
    activity: joi.array().items(joi.object({
      title: joi.string()
    }).default([]))
  })
)
// result
{
  id: ObjectId("asdasd...")
  title: "title here",
  activity: []
}
```

**Comment by yoitsro** [comment]
Thanks for that. I'm a little busy right now, but if you could maybe take a look, I'd be able to review a PR :)

**Comment by microcipcip** [comment]
It seems that I just need to add `minimize: false,` as schema option. I'll close this issue if this works.

**Comment by yoitsro** [comment]
Yeah, I think that works since it's Mongoose which is responsible for stripping out empty arrays.
