### ISSUE TITLE
How do you handle virtuals?

### ISSUE THREAD

**Issue by anthonator** [yoitsro/joigoose#2]
Is it possible to handle virtual fields? There are instances where I want to validate a virtual field and (obviously) not persist it.

**Comment by yoitsro** [comment]
It's not something I've looked into just yet. I'll take a look sometime, but by all means feel free to dig into the code yourself and see what you can come up with :)

**Comment by danielgreane** [comment]
@anthonator I've been able to achieve virtuals by creating a new Mongoose schema from the returned Joigoose object. Example below:

```
const joiAuthorSchema = Joi.object({
  name: Joi.string().required()
});

const joigooseSchema = Joigoose.convert(joiAuthorSchema);
let mongooseSchema = new Mongoose.Schema(joigooseSchema);

mongooseSchema.virtual('posts', {
  ref: 'Post',
  localField: '_id',
  foreignField: 'shop'
});

const AuthorModel = Mongoose.model('Author', mongooseSchema); 

```

**Comment by yoitsro** [comment]
@anthonator does that work for you?

**Comment by yoitsro** [comment]
Closing: https://github.com/yoitsro/joigoose/issues/2#issuecomment-266282393.
