### ISSUE TITLE
Allow to provide enum in string data type 

### ISSUE THREAD

**Issue by JeromeDeLeon** [yoitsro/joigoose#24]
Like in mongoose that allows developers to provide enum validator like this:

`var personSchema = new Schema({
       ....
      gender: {
           type: String,
           enum: ['F', 'M']
      }
    });`

**Comment by yoitsro** [comment]
Hey @JeromeDeLeon, sorry about the delay. I'm a little busy at the moment, so I'm not sure when I'll have chance to look at this, but feel free to submit a PR and I'll take a look :)

**Comment by g-div** [comment]
If I undestand this correctly the values passed to [`.valid(...values)`](https://hapi.dev/family/joi/?v=16.1.8#anyvalidvalues---aliases-equal) should be passed to the `enum` property. 
The problem I see there is that *Joi* implements `.valid(...values)` for `any` type, while mongoose only accept this property for keys of `type` `String`.
Assumed that it is ok that it will only works for strings, I will maybe try to submit a PR soon.

**Comment by yoitsro** [comment]
Closing this, but I'll reopen if necessary.
