### ISSUE TITLE
Joi v16 (please help!)

### ISSUE THREAD

**Issue by yoitsro** [yoitsro/joigoose#27]
Joi got a teeny tiny update... https://github.com/hapijs/joi/issues/2037

At the moment, I don't have bags of time to attempt a refactor of Joigoose. If anybody feels like helping chip away, please let me know. The more, the merrier :)

**Comment by g-div** [comment]
I hope #29 can help here :rescue_worker_helmet:

**Comment by yoitsro** [comment]
Hey @g-div! Thank you so much for this 🙏 I'll try to take a look at this asap :)
