### ISSUE TITLE
Is there an example of how you can make joi error messages for form more user friendly?

### ISSUE THREAD

**Issue by bjohnson-ionrev** [yoitsro/joigoose#28]
JOI has a language.js that has meaningful error messages.

**Comment by bjohnson-ionrev** [comment]
We are using feathers-mongoose-casl that implements joigoose for it's schema and schema validation. Then on the font-end we are using vue.js with feathers-vuex.

**Comment by yoitsro** [comment]
Hi @bjohnson-ionrev, please can you post an example of the error messages you're currently getting?
