### ISSUE TITLE
Converted mongoose schema doesn't allow middleware (pre and post hooks)

### ISSUE THREAD

**Issue by josefransaenz** [yoitsro/joigoose#4]
Very nice module, but I couldn't add middleware to converted mongoose schema. Are you already working on this? Is there any workaround?

**Comment by josefransaenz** [comment]
I found a solution: just create again the mongoose schema but this time using the mongoose schema constructor like this:
`var Mongoose = require('mongoose');
var Joigoose = require('joigoose')(Mongoose);
var joiSchema = Joi.object({...});
var convertedSchema= Joigoose.convert(joiSchema);

schemaWithMiddleware = new mongoose.Schema(convertedSchema);`

Now I can add my middleware and create the model:
`schemaWithMiddleware.pre('save', function(next) {...});
var MyModel= mongoose.model('MyModel', schemaWithMiddleware);`

**Comment by yoitsro** [comment]
Yep, this is the way to do it. Are you happy for me to close this?

**Comment by josefransaenz** [comment]
Yes

**Comment by microcipcip** [comment]
@yoitsro I think this should be in the documentation. I was having errors with statics and methods.

**Comment by yoitsro** [comment]
@microcipcip sorry about that. Please could you submit a PR updating the docs?

**Comment by microcipcip** [comment]
@yoitsro I will! BTW your module is excellent :-)

**Comment by mikepanayotov** [comment]
Hello, seems this doesn't work anymore. Do you have some info?

```const Mongoose = require('mongoose');
const Joigoose = require('joigoose')(Mongoose);
const validationSchema = require('./schema');

const MongooseSchema = new Mongoose.Schema(Joigoose.convert(validationSchema),
{
    timestamps: true
}
);

MongooseSchema.post('remove', function(doc) {
    // 'this' is the client being removed. Provide callbacks here if you want
    // to be notified of the calls' result.
    //Vouchers.remove({user_id: this._id}).exec();
    console.log('has been removed', doc);
});

MongooseSchema.post('update', function(doc) {
    // 'this' is the client being removed. Provide callbacks here if you want
    // to be notified of the calls' result.
    //Vouchers.remove({user_id: this._id}).exec();
    console.log('has been updated', doc);
});

module.exports = Mongoose.model('data', MongooseSchema);```

**Comment by yoitsro** [comment]
Hey @mikepanayotov.

Have you tried doing this without Joigoose? Does it work then?

**Comment by mikepanayotov** [comment]
@yoitsro, looks like NO. :( That's strange!

**Comment by yoitsro** [comment]
It looks like this is a mongoose issue then :( It might be worth having a look at their open issues to see if anyone else is experiencing anything similar.
