### ISSUE TITLE
Using Object References 

### ISSUE THREAD

**Issue by iyosayi** [yoitsro/joigoose#40]
While working on a schema, I tried using the Object References in the schema and for some reason, it fails to validate the path that the Object Reference was called.

Here is a snippet of my Schema:

``` const Mongoose = require("mongoose");
const Joigoose = require("joigoose")(Mongoose);
const Joi = require("@hapi/joi");

const activitySchema = Joi.object({
  activityName: Joi.string(),
  tasks: Joi.string().meta({ _mongoose: {type: "ObjectId", ref: "Task"  } }),
});

const mongooseSchema = new Mongoose.Schema(Joigoose.convert(activitySchema));

module.exports = Mongoose.model("Activity", mongooseSchema);
```

Error: 
```[ValidationError]: Activity validation failed: tasks: Cast to ObjectID failed for value "something" at path "tasks" ```

Error: 
```MongooseError [CastError]: Cast to ObjectID failed for value "something" at path "tasks" ```

**Comment by yoitsro** [comment]
Hi @iyosayi. It looks like this is happening because the value `something` can't be cast to an ObjectID. Please ensure your ObjectID is a [valid hexadecimal string](https://docs.mongodb.com/manual/reference/method/ObjectId/#ObjectId).
