### ISSUE TITLE
How to populate an array of ObjectIds?

### ISSUE THREAD

**Issue by LukeXF** [yoitsro/joigoose#43]
I see your homepage documentation you can create an objectId reference
```
bestFriend: Joi.string().meta({
    _mongoose: { type: "ObjectId", ref: "User" },
}),
```

How would you build an array of ObjectId references using joigoose?

```
bestFriends: Joi.array().items(Joi.string().meta({
    _mongoose: {type: "ObjectId", ref: "User"},
})),
```

Because my populate isn't working. Trying to see if this is correct syntax first before I investigate Mongoose.

**Comment by yoitsro** [comment]
Hey @LukeXF. That syntax should work. If it doesn't, please can you confirm this bug by writing a test similar to https://github.com/yoitsro/joigoose/blob/master/test/index.js#L145 and confirming that it definitely isn't working?

Please submit that as a PR. If you're feeling up to it, I'd appreciate the help in fixing it if it is a bug! 🤞

**Comment by yoitsro** [comment]
Hey @LukeXF. Closing this for now, but feel free to reopen it if you get a chance to work on it :)

**Comment by LukeXF** [comment]
> Hey @LukeXF. Closing this for now, but feel free to reopen it if you get a chance to work on it :)

I wasn't able to look into this further, still doesn't work but I don't have time to fix it yet. Will message if I have time in the future. Thank you though, appreciate your support!
