### ISSUE TITLE
@hapi/joi dependency becoming joi

### ISSUE THREAD

**Issue by lambertkevin** [yoitsro/joigoose#46]
```joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)```
https://www.npmjs.com/package/@hapi/joi

This breaking change is causing an error for people that already upgraded their dependencies that can't be fixed with package-lock unfortunately as far as i know:

```Error: Cannot mix different versions of joi schemas```

**Comment by yoitsro** [comment]
Hey @lambertkevin.

Thanks for this! It looks like it's going to have to be a major version change for joigoose as well then.
