### ISSUE TITLE
Embedded documents?

### ISSUE THREAD

**Issue by at0g** [yoitsro/joigoose#7]
From this code:

```
Joi.array().items({ foo: Joi.string() })
```

I get this error: `Cannot read property '$__' of undefined (500)`

But this works ok.
`Joi.array().items(Joi.string())`

**Comment by yoitsro** [comment]
What if you try `Joi.array().items(Joi.object({ foo: Joi.string() }))`?

**Comment by svda** [comment]
I ran into a similar issue. The type detection appears not to be working as it should:
{ type: [ [Object] ] }

**Comment by paul42** [comment]
when you're in Joi.array().items({}) do you need to return a Joi.object().keys({ foo: Joi.string()}) ?

**Comment by yoitsro** [comment]
I'm going to be taking a look at this very soon. I'll keep you updated.

**Comment by yoitsro** [comment]
It looks like it's working for me. I've just added a test to confirm this and I'll push shortly.
