### ISSUE TITLE
Wrong validation for nested objects with optional properties with required properties

### ISSUE THREAD

**Issue by tsipenyuk** [yoitsro/joigoose#73]
If 
- the top joi schema `User` 
- has an optional attribute `name`, and 
- `name` is described by child schema `joiNameSchema` with a required attribute `lastname`, 

then 
- `name` itself becomes required in `User`
-  but it should not be required.

In other words, here is the desired behavior: if `name` is an object, then it must have `lastname`, but `name` itself should not be required.

Here is a test that fails when inserted into `test/index.js`:
```js
    it("should deal with objects that have optional properties that have required properties", async () => {
      const joiNameSchema = O({
        firstname: S(),
        lastname: S().required(),
      });

      const joiUserSchema = O({
        name: joiNameSchema, // note that name is not required
      });

      const mongooseUserSchema = Joigoose.convert(joiUserSchema);
      const User = Mongoose.model("User7", mongooseUserSchema);

      const newUser = new User({
        name: undefined, // since name is not required, this should be OK
      });

      try {
        await newUser.validate();
      } catch (err) {
        expect(err.message).to.equal(null);
      }
    });
```

**Comment by tsipenyuk** [comment]
Oh, sorry, this is a duplicate of [this issue](https://github.com/yoitsro/joigoose/issues/25).

I will look if I can fix it locally.

**Comment by tsipenyuk** [comment]
Jeez, that is indeed not so straightforward as one could have hoped...

**Comment by yoitsro** [comment]
Hey @tsipenyuk. It's been a while since I looked at it, but yeah, it wasn't super straightforward. You don't fancy a challenge, do you? :)

**Comment by tsipenyuk** [comment]
I am really strapped for time, but I'll try to poke around if I have a few hours to spare.

For posteriority, my attempt so far was to add 
```ts
    const description = joiObject.describe()
    if (description?.flags?.presence !== "required") {
      output.required = false;
    }
```
at the end of the `  if (joiObject.type === "object") {` block (after line 95).

When running this with the test I presented above and adding a console log before the return, like so:
```ts
console.log('debug@at return', JSON.stringify(output))
```
I get 
```ts
debug@at return {"name":{"firstname":{"validate":{}},"lastname":{"validate":{},"required":true},"required":false},"required":false}
```
compared to the unmodified version that logs
```ts
debug@at return {"name":{"firstname":{"validate":{}},"lastname":{"validate":{},"required":true}}}
```

However, this does not work, probably due to some quirk of Mongoose, probably the same reason as outlined by the comment in line 109, `  // We don't want the required key added onto objects, hence why its here.`

The fact that schema generation is dynamic makes it a bit trickier to debug than static converters (like joi-to-typescript or joi-to-swagger)...

**Comment by FullmetalBober** [comment]
Guys, i'm found a way how to get this validation condition:
```
const joiObj = Joi.object({
  age: Joi.string(),
  name: {
    type: Joi.object({
      first: Joi.string(),
      last: Joi.string().required(),
    }),
  },
});
```
So in this schema we have such fields:

- age - optional
- name - optional
- name.first - required
- name.last - required

Hope this trick will help someone 😁

**Comment by tsipenyuk** [comment]
Whoa, in this case "name" becomes optional? I will definitely check it out,
thank you so much!
