### ISSUE TITLE
DeprecationWarning: Implicit async custom validators

### ISSUE THREAD

**Issue by throrin19** [yoitsro/joigoose#9]
Hi,

I have this error on document save with a schema generate by `joigoose` :

> DeprecationWarning: Implicit async custom validators (custom validators that take 2 arguments) are deprecated in mongoose >= 4.9.0. See http://mongoosejs.com/docs/validation.html#async-custom-validators for more info.

**Comment by yoitsro** [comment]
Hey Benjamin,

Thanks for that. I'm just taking a look at that now. I'll be sure to close this issue when I've released an update!

**Comment by yoitsro** [comment]
That's it closed now. Just about to publish version 2.0.0 :)
